blank_issues_enabled: true
contact_links:
  - name: â“ Questions
    url: https://discourse.phantomsw.com
    about: Ask your question on the Node-RED forum
  - name: â­ï¸ Feature Request
    url: https://discourse.phantomsw.com/c/development/feature-requests
    about: Discuss your request with the community
  - name: ğŸ—‚ Documentation
    url: https://phantomsw.com/docs
    about: Go straight to the documentation
  - name: ğŸ’¬ Slack
    url: https://phantomsw.com/slack
    about: Chat about the project on our slack team
